ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: yarn && gp sync-done install

  - name: receiver
    before: |
      export REDIS_URL=redis://root:pass@51.91.140.153:6379
      export CONCURRENCY=2
      export PORT=3000
      export API_URL=$(gp url 3000)
    command: gp sync-await install && yarn start:receiver

  - name: sender
    before: |
      export REDIS_URL=redis://root:pass@51.91.140.153:6379
      export CONCURRENCY=2
      export PORT=3000
      export API_URL=$(gp url 3000)
    command: gp sync-await install && yarn start:sender
    
    openMode: split-right